// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ReferralDemo.Data;

#nullable disable

namespace ReferralDemo.Migrations
{
    [DbContext(typeof(ReferralDbContext))]
    [Migration("20261007004919_InitialPostgres")]
    partial class InitialPostgres
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.31")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ReferralDemo.Models.Patient", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("pk_patients");

                    b.ToTable("patients", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "P001",
                            Name = "Alice Smith",
                            Status = "in_care"
                        },
                        new
                        {
                            Id = "P002",
                            Name = "Robert Smith",
                            Status = "discharged"
                        },
                        new
                        {
                            Id = "P003",
                            Name = "Maria Gonzalez",
                            Status = "in_care"
                        },
                        new
                        {
                            Id = "P004",
                            Name = "James Smith",
                            Status = "pending_admission"
                        });
                });

            modelBuilder.Entity("ReferralDemo.Models.Referral", b =>
                {
                    b.Property<string>("PatientId")
                        .HasColumnType("text")
                        .HasColumnName("patient_id");

                    b.Property<DateTime?>("DueDate")
                        .HasColumnType("date")
                        .HasColumnName("due_date");

                    b.Property<string>("NextStep")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("next_step");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("provider");

                    b.HasKey("PatientId")
                        .HasName("pk_referrals");

                    b.ToTable("referrals", (string)null);

                    b.HasData(
                        new
                        {
                            PatientId = "P001",
                            DueDate = new DateTime(2026, 10, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NextStep = "Initial assessment scheduled",
                            Provider = "Riverside Home Health"
                        },
                        new
                        {
                            PatientId = "P003",
                            DueDate = new DateTime(2026, 9, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NextStep = "Awaiting insurance authorization",
                            Provider = "Sunrise Physical Therapy"
                        });
                });

            modelBuilder.Entity("ReferralDemo.Models.Visit", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date");

                    b.Property<string>("PatientId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("patient_id");

                    b.HasKey("Id")
                        .HasName("pk_visits");

                    b.ToTable("visits", (string)null);
                });

            modelBuilder.Entity("ReferralDemo.Models.Referral", b =>
                {
                    b.HasOne("ReferralDemo.Models.Patient", null)
                        .WithOne()
                        .HasForeignKey("ReferralDemo.Models.Referral", "PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_referrals_patients_patient_id");
                });
#pragma warning restore 612, 618
        }
    }
}
